# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'animated_chart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for animated_chart
  pod "Macaw", "0.9.6"

end
